import AppHeader from '@/components/Header/Header'
import '../styles/globals.scss'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/redux/provider/provider'
import AuthWrapper from '@/features/Authentication/components/AuthWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vacation Homes & Condo Rentals',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AppHeader />
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </ReduxProvider>
      </body>
    </html>
  )
}
