import VerifyAccount from "@/features/Authentication/components/VerifyAccount";

export const metadata = {
    title: 'Verify your account',
    description: 'Generated by create next app',
}

function VerifyAccountPage() {
    return (
        <main className="app-container">
            <VerifyAccount />
        </main>
    );
}

export default VerifyAccountPage;